export const FETCH_GAMES_BEGIN = "FETCH_GAMES_BEGIN";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FAILURE = "FETCH_GAMES_FAILURE";

export const SET_SELECTED_ATHLETE = "SET_SELECTED_ATHLETE";

export const FETCH_ATHLETE_MEDALS_BEGIN = "FETCH_ATHLETE_MEDALS_BEGIN";
export const FETCH_ATHLETE_MEDALS_SUCCESS = "FETCH_ATHLETE_MEDALS_SUCCESS";
export const FETCH_ATHLETE_MEDALS_FAILURE = "FETCH_ATHLETE_MEDALS_FAILURE";
