export const LIST_ATHLETES_BEGIN = "LIST_ATHLETES_BEGIN";
export const LIST_ATHLETES_SUCCESS = "LIST_ATHLETES_SUCCESS";
export const LIST_ATHLETES_FAILURE = "LIST_ATHLETES_FAILURE";

export const FETCH_ATHLETE_BY_ID_BEGIN = "FETCH_ATHLETE_BY_ID_BEGIN";
export const FETCH_ATHLETE_BY_ID_SUCCESS = "FETCH_ATHLETE_BY_ID_SUCCESS";
export const FETCH_ATHLETE_BY_ID_FAILURE = "FETCH_ATHLETE_BY_ID_FAILURE";
